{% set name = "aws-error-utils" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aws-error-utils-{{ version }}.tar.gz
  sha256: 164f2a5bdd69c4cecc647d6e080c21243472c44c4d3caba15908f69d7fcfe16b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python !=3.0,!=3.1,!=3.2
  run:
    - botocore
    - python !=3.0,!=3.1,!=3.2

test:
  imports:
    - aws_error_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/benkehoe/aws-error-utils
  summary: Error-handling functions for boto3/botocore
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
